# Generated by Django 5.1.3 on 2025-01-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='static/images/testimonials/test2.jpg', upload_to='testimonials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
